1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
import numpy as np

a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a1 = a.reshape(3, 4)
a2 = a.reshape(2, 6)
a3 = a.reshape(6, 2)
a4 = a.reshape(4, 3)
a5 = a.reshape(1, 12)

print("Размерность a1: {}".format(a1.ndim))
print("Размерность a2: {}".format(a2.ndim))
print("Размерность a3: {}".format(a3.ndim))
print("Размерность a4: {}".format(a4.ndim))
print("Размерность a5: {}".format(a5.ndim))

Размерность a1: 2
Размерность a2: 2
Размерность a3: 2
Размерность a4: 2
Размерность a5: 2


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [16]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(12, -1)
a4 = a.reshape(-1, 4)
a5 = a.reshape(-1, 12)

print("Размерность a1: {}".format(a1.ndim))
print("Размерность a2: {}".format(a2.ndim))
print("Размерность a3: {}".format(a3.ndim))
print("Размерность a4: {}".format(a4.ndim))
print("Размерность a5: {}".format(a5.ndim))

Размерность a1: 2
Размерность a2: 2
Размерность a3: 2
Размерность a4: 2
Размерность a5: 2


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Ответ: Из-за внутренней структуры размерность такого массива равна 2.

In [17]:
print(a3)
print("Размерность a3: {}".format(a5.ndim))

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Размерность a3: 2


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [22]:
import numpy.random as rd

a = rd.randn(3, 4)
print(a)

b = a.flatten()
print(b)

print(a.size == b.size)

[[-1.11918906  0.71418709 -0.20984384 -2.13648912]
 [ 0.05905328  1.3019928   1.11709824 -1.64489977]
 [ 1.15924325  0.44122828 -1.17068689  0.24046998]]
[-1.11918906  0.71418709 -0.20984384 -2.13648912  0.05905328  1.3019928
  1.11709824 -1.64489977  1.15924325  0.44122828 -1.17068689  0.24046998]
True


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [25]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [27]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


Массивы a и b одинаковые.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [34]:
a = np.zeros((3, 2))
b = np.ones((2, 2))

c = np.vstack((a, b))

print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [57]:
from numpy.linalg import inv

a = np.arange(0, 12, 1)
A = a.reshape(4, 3).copy()
print(f'Матрица A: \n {A}\n')

At = np.transpose(A)
print(f'Матрица At: \n {At}\n')

B = np.dot(A, At)
print(f'Матрица B: \n {B}\n')

print(B.size)

Матрица A: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Матрица At: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

Матрица B: 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

16


Определитель матрицы B равен 0, следовательно, обратную матрицы вычислить невозможно.

In [59]:
np.linalg.det(B)

0.0

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [92]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [95]:
a = np.random.randint(0, 16, 16)
print(a)

[ 3 12 14 10  7 12  4  6  9  2  6 10 10  7  4  3]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [96]:
C = a.reshape((4,4)).copy()
print(C)

[[ 3 12 14 10]
 [ 7 12  4  6]
 [ 9  2  6 10]
 [10  7  4  3]]


In [98]:
D = 10 * C + B
print(f'Матрица D: \n {D}\n')
print(f'Определитель матрицы D: \n {np.linalg.det(D)}\n')
D_inv = np.linalg.inv(D)
print(f'Обратная матрица D: \n {D_inv}\n')

Матрица D: 
 [[ 35 134 163 132]
 [ 84 170 126 182]
 [113 106 209 312]
 [132 192 252 332]]

Определитель матрицы D: 
 21320000.000000034

Обратная матрица D: 
 [[-0.0421257  -0.04781989 -0.07423077  0.11272233]
 [ 0.00713133  0.01837899  0.00807692 -0.02050094]
 [-0.00235084 -0.03018386 -0.02807692  0.04386679]
 [ 0.01440901  0.03129456  0.04615385 -0.06324578]]



13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [101]:
pos_value = D_inv > 0
neg_value = D_inv < 0

In [102]:
D_inv[pos_value ] = 1
D_inv[neg_value] = 0
print(D_inv)

[[0. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 0.]]


In [103]:
E = np.where(D_inv, B, C)
print(E)

[[  3  12  14  32]
 [ 14  50  86   6]
 [  9   2   6 212]
 [ 32 122 212   3]]
